export const site = {
  name: "Causeway Motors",
  tagline: "We Make Your Auto Problems Disappear, Fast.",
  foundedYear: 1966,
  phone: "09 489 5790",
  phoneHref: "tel:+6494895790",
  email: "service@causewaymotors.co.nz",
  address: {
    street: "63 Barrys Point Road",
    suburb: "Takapuna",
    city: "Auckland",
    postcode: "0622",
    country: "New Zealand",
  },
  hours: [
    { day: "Mon – Fri", open: "7:30", close: "17:00" },
    { day: "Saturday", open: "Closed", close: "" },
    { day: "Sunday", open: "Closed", close: "" },
  ],
  bookingHref: "/contact#book",
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "About", href: "/about" },
    { label: "Contact", href: "/contact" },
  ],
  specialties: [
    "Audi",
    "BMW",
    "Mercedes-Benz",
    "Volkswagen",
    "Volvo",
    "Saab",
    "Subaru",
    "Toyota",
    "Honda",
    "Mazda",
    "Nissan",
  ],
  accreditations: ["AA Motoring Approved", "Afterpay accepted"],
};
